name: Deploy React App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.15'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 95.163.220.161
          username: root
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            mkdir -p /opt/projects/nameless/os/frontend-core
            rm -rf /opt/projects/nameless/os/frontend-core/*

      - name: Copy build files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 95.163.220.161
          username: root
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "dist/*"
          target: "/opt/projects/nameless/os/frontend-core/"
          strip_components: 1